### ISSUE TITLE
Локальная сборка фронтенда на windows

### ISSUE THREAD

**Issue by VladislavPetyukevich** [Agylam/web#44]
На windows нельзя установить зависимости локально, а это нужно для того, чтоб все типы подтянулись.
Установить зависимости не даёт `@esbuild/linux-x64`.
Надо исправить это проблему, т. к. без сборки на windows никуда. Так-то ТОП 1 ОС среди разработчиков: https://survey.stackoverflow.co/2022#section-most-popular-technologies-operating-system

**Comment by MIMBOL228** [comment]
Решено
