### ISSUE TITLE
Обновить авторизацию

### ISSUE THREAD

**Issue by MIMBOL228** [Agylam/web#5]
Имеется ныняшняя система авторизации (IndexPage.tsx:18). Она принимает токен в ответе от API и кладёт его в LocalStorage(LS) и перебрасывает на другую страницу /schedule . После этого, любые другие страницы проверяют наличие и актуальность этого токена (только по времени), а в случае его невалидности стирают его и перебрасывают на индексовую страницу. Необходимо модернизировать систему. Ожидаемый алгоритм. Система принимает 2 токена при запросе в /user/auth (access и refresh) и кладёт их в LS. Access токен живёт несколько минут, после чего становится не активным, нужно обновлять через refresh GET /user/refresh_token/:refresh_token . Ответ такой же как и при авторизации.

**Comment by MIMBOL228** [comment]
Новый BackEnd находится в dev ветке

**Comment by VladislavPetyukevich** [comment]
https://swr.vercel.app/ru
